### ISSUE TITLE
Problem when duplicating product

### ISSUE THREAD

**Issue by MaxOutil** [shoppingflux/module-magento#27]
When duplicating a product master record, an SQL error message is displayed:

> SQLSTATE[23000]: Integrity contraint violation : 1062 Duplicate entry '2' for key 'SF_E_F_UNIQUE', query was: INSERT INTO 'shoppingflux_export_flux' ('product_id, 'store_id', update_needed') VALUES (?, ?, ?)

It seems to sku null of the new product.
Have you ever noticed this problem?

**Comment by blmage** [comment]
Thanks for reporting this problem! This should be fixed by 517c3faf726ea5b390b9f692f5568d0f3da3854d.
